version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5432:5432
    volumes:
      - postgresData:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#       - POSTGRESQL_USERNAME=my_user
#       - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_POSTGRES_PASSWORD=bassBoosted
#       - POSTGRESQL_DATABASE=my_database
      

volumes:
  postgresData:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\Users\Marsik\Desktop\Java обучение\volumeForPostgres'